<?php require 'inc/lib.php';need('edit');$p=db();$id=(int)($_GET['id']??0);$h=[];$M=[];
if($id){$s=$p->prepare('SELECT * FROM households WHERE id=?');$s->execute([$id]);$h=$s->fetch()?:[];if(!$h)exit('Not found');$s=$p->prepare('SELECT * FROM members WHERE household_id=? ORDER BY id');$s->execute([$id]);$M=$s->fetchAll();}
$oldH=$h;$oldM=$M;$err='';$warn='';
function mkey($M){return json_encode(array_map(fn($m)=>[trim($m['name']??''),(string)($m['age']??''),$m['sex']??'',$m['edu']??'',$m['occ']??'',number_format((float)($m['income']??0),2,'.',''),$m['remarks']??''],array_values(array_filter($M,fn($m)=>trim($m['name']??'')!==''))));}
if($_SERVER['REQUEST_METHOD']==='POST'){check();$P=$_POST;$n=fn($k)=>($P[$k]??'')===''?null:$P[$k];$h=$P+$h;$M=array_values($P['m']??[]);
if(trim($P['ln'])===''||trim($P['fn'])===''||trim($P['brgy'])===''){$err='Barangay, last name and first name are required.';}
else{$dups=[];
if(empty($P['force'])){$bd=$n('birthdate');$q=$p->prepare('SELECT id,household_code,ln,fn,mn,brgy,birthdate FROM households WHERE id<>? AND LOWER(TRIM(ln))=? AND LOWER(TRIM(fn))=? AND (birthdate IS NULL OR ? IS NULL OR birthdate=?)');$q->execute([$id,mb_strtolower(trim($P['ln'])),mb_strtolower(trim($P['fn'])),$bd,$bd]);$dups=$q->fetchAll();}
if($dups){$warn='<div class="warnbox"><b>Possible duplicate household.</b> A record with the same head of household already exists:<ul>';foreach($dups as $d)$warn.='<li>'.e($d['household_code']?:'#'.$d['id']).' – '.e("$d[ln], $d[fn] $d[mn]").' ('.e($d['brgy']).($d['birthdate']?', born '.e($d['birthdate']):'').') <a href="sheet.php?id='.$d['id'].'" target="_blank">open</a></li>';$warn.='</ul>Check the existing record first. If this is a different household, tick <label><input type="checkbox" name="force" value="1" style="width:auto"> save anyway</label> and press Save again.</div>';}
else{$cols=['brgy','interview_date','ln','fn','mn','age','sex','birthdate','civil','edu','occ','income','religion','contact','total_members','total_families','house_type','house_own','electricity','chronic','chronic_spec','philhealth','ph_no','ph_cat','interviewer'];foreach(IND as $k=>$_)$cols[]='s_'.$k;
$dflt=['income'=>0,'total_members'=>1,'total_families'=>1];foreach(IND as $k=>$_)$dflt['s_'.$k]=0;$vals=array_map(fn($c)=>in_array($c,['interview_date','birthdate','age'])?$n($c):(isset($dflt[$c])?(($P[$c]??'')===''?$dflt[$c]:$P[$c]):($P[$c]??'')),$cols);
$norm=fn($c,$x)=>$c==='income'?number_format((float)$x,2,'.',''):(string)$x;
if($id){$chg=[];foreach($cols as $i=>$c){$o=$norm($c,$oldH[$c]??'');$nv=$norm($c,$vals[$i]??'');if($o!==$nv)$chg[]="$c: '$o' → '$nv'";}
if(mkey($oldM)!==mkey($M))$chg[]='family members changed';
$p->prepare('UPDATE households SET '.implode('=?,',$cols).'=? WHERE id=?')->execute([...$vals,$id]);$p->prepare('DELETE FROM members WHERE household_id=?')->execute([$id]);
logact('EDIT',$id,($oldH['household_code']??'')." $P[ln], $P[fn] – ".($chg?implode('; ',$chg):'saved without changes'));}
else{$p->prepare('INSERT INTO households('.implode(',',$cols).',created_by) VALUES('.str_repeat('?,',count($cols)).'?)')->execute([...$vals,user()['id']]);$id=(int)$p->lastInsertId();$code=sprintf('HH-%s-%04d',date('Y'),$id);$p->prepare('UPDATE households SET household_code=? WHERE id=?')->execute([$code,$id]);
logact('ADD',$id,"Added $code $P[ln], $P[fn] ($P[brgy])".(!empty($P['force'])?' – saved despite duplicate warning':''));}
$ins=$p->prepare('INSERT INTO members(household_id,name,age,sex,edu,occ,income,remarks) VALUES(?,?,?,?,?,?,?,?)');
foreach($M as $m){if(trim($m['name'])==='')continue;$ins->execute([$id,$m['name'],$m['age']===''?null:$m['age'],$m['sex'],$m['edu'],$m['occ'],$m['income']===''?0:$m['income'],$m['remarks']]);}
header('Location: sheet.php?id='.$id);exit;}}}
function inp($k,$l,$t='text',$h=[]){return "<div><label>$l<input type='$t' name='$k' value='".e($h[$k]??'')."'></label></div>";}
function rad($k,$o,$h){$s='<div class="chk">';foreach($o as $x)$s.="<label><input type='radio' name='$k' value='".e($x)."'".(($h[$k]??'')===$x?' checked':'')." onchange='auto()'>".e($x).'</label>';return $s.'</div>';}
$v=fn($k)=>e($h[$k]??'');head('Household form');?><h2><?=$id?'Edit':'New'?> household profile</h2><div class="card"><p class="bad"><?=e($err)?></p>
<form method="post"><input type="hidden" name="t" value="<?=csrf()?>">
<?=$warn?><div class="f"><?=inp('brgy','Barangay','text',$h)?><?=inp('interview_date','Date of interview','date',$h)?></div>
<h3>I. Family information</h3><div class="f"><?=inp('ln','Last name','text',$h)?><?=inp('fn','First name','text',$h)?><?=inp('mn','Middle name','text',$h)?><?=inp('age','Age','number',$h)?><div><label>Sex<select name="sex"><option></option><?php foreach(['Male','Female'] as $x)echo '<option'.(($h['sex']??'')==$x?' selected':'').">$x</option>";?></select></label></div><?=inp('birthdate','Birthdate','date',$h)?><?=inp('civil','Civil status','text',$h)?><?=inp('edu','Educational attainment','text',$h)?><?=inp('occ','Occupation / establishment','text',$h)?><div><label>Monthly income (₱)<input type="number" step="0.01" name="income" value="<?=$v('income')?>" oninput="auto()"></label></div><?=inp('religion','Religion','text',$h)?><?=inp('contact','Contact number','text',$h)?></div>
<h3>II. Family composition</h3><div class="scroll"><table><tr><th>#</th><th>Name</th><th>Age</th><th>Sex</th><th>Educ. attainment</th><th>Occupation / establishment</th><th>Monthly income</th><th>Remarks (SC/PWD/SP/OSY/OFW/IP/4P's)</th></tr>
<?php for($i=0;$i<10;$i++){$m=$M[$i]??[];echo '<tr><td>'.($i+1).'</td>';foreach(['name'=>170,'age'=>60,'sex'=>70,'edu'=>110,'occ'=>140,'income'=>90,'remarks'=>110] as $k=>$w)echo "<td><input name='m[$i][$k]' value='".e($m[$k]??'')."' style='min-width:{$w}px'".($k=='income'?" class='minc' oninput='auto()'":'').($k=='name'?" class='mname' oninput='auto()'":'')."></td>";echo '</tr>';}?></table></div>
<div class="f" style="margin-top:8px"><div><label>Total number of household members<input type="number" name="total_members" id="tm" value="<?=$v('total_members')?>" oninput="auto()"></label></div><div><label>Total number of families<input type="number" name="total_families" value="<?=$v('total_families')?>"></label></div></div>
<p style="margin-top:8px">Combined monthly income: <b id="comb">₱0.00</b> <span class="mut">(head's income is counted once; if the head is also listed in the table, the larger of the two amounts is used)</span></p>
<h3>III. Housing condition</h3><div class="f"><div><label>Type of house</label><?=rad('house_type',['Concrete','Semi-concrete','Makeshift'],$h)?></div><div><label>House ownership</label><?=rad('house_own',['Owned','Rented','Living with Relatives','Informal Settler'],$h)?></div><div><label>Electricity</label><?=rad('electricity',['Yes','No'],$h)?></div></div>
<h3>IV. Health and nutrition</h3><div class="f"><div><label>Any family member with chronic illness?</label><?=rad('chronic',['Yes','No'],$h)?><?=inp('chronic_spec','If yes, specify','text',$h)?></div><div><label>With PhilHealth?</label><?=rad('philhealth',['Yes','No'],$h)?><?=inp('ph_no','PhilHealth #','text',$h)?><?=inp('ph_cat','Category','text',$h)?></div></div>
<h3>V. Score sheet</h3><p class="mut">Select a score for each indicator. The housing score is suggested from the house type; you can change it.</p><div class="f"><?php foreach(IND as $k=>$l){echo "<div><label>$l<select name='s_$k' id='s_$k'>";foreach(OPT[$k] as $i=>$o)echo "<option value='$i'".((int)($h['s_'.$k]??0)===$i?' selected':'').">$i – ".e($o).'</option>';echo '</select></label></div>';}?></div>
<div style="margin-top:14px"><?=inp('interviewer','Interviewer / Social worker','text',$h)?></div>
<p style="margin-top:16px"><button class="btn p">Save household</button> <a class="btn" href="households.php">Cancel</a></p></form></div>
<script>function auto(){const t=document.querySelector('[name=house_type]:checked');if(t)document.getElementById('s_hou').value=['Concrete','Semi-concrete','Makeshift'].indexOf(t.value)}
const tk=s=>(s.toLowerCase().match(/[\p{L}\p{N}]+/gu)||[]),V=n=>(document.querySelector('[name="'+n+'"]')||{value:''}).value;
function comb(){let hi=+V('income')||0,oth=0,seen=false;const need=[...tk(V('fn')),...tk(V('ln'))],ht=[...need.slice(0,tk(V('fn')).length),...tk(V('mn')),...tk(V('ln'))];
for(let i=0;i<10;i++){const t=tk(V('m['+i+'][name]')),inc=+V('m['+i+'][income]')||0;if(!seen&&t.length&&need.every(x=>t.includes(x))&&t.every(x=>ht.includes(x))){seen=true;hi=Math.max(hi,inc)}else oth+=inc}
document.getElementById('comb').textContent='₱'+(hi+oth).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2})}
document.addEventListener('input',comb);comb();</script><?php foot();
