<?php require 'inc/lib.php';need();$p=db();$s=$p->prepare('SELECT * FROM households WHERE id=?');$s->execute([(int)$_GET['id']]);$h=$s->fetch();if(!$h)exit('Not found');
$s=$p->prepare('SELECT * FROM members WHERE household_id=? ORDER BY id');$s->execute([$h['id']]);$M=$s->fetchAll();$t=total($h);$c=klass($t);
$cb=fn($a,$b)=>($a===$b?'☑':'☐').' '.e($b);$u=fn($x)=>'<span class="ul">'.e($x).'</span>';
head('Data sheet');?><div class="noprint" style="margin-bottom:12px"><button class="btn p" onclick="print()">Print data sheet</button> <a class="btn" href="households.php">Back to list</a></div>
<div class="sheet"><h2 style="text-align:center">HOUSEHOLD PROFILE FORM</h2><p style="text-align:center">Household ID: <b><?=e($h['household_code'])?></b></p><p>Barangay: <?=$u($h['brgy'])?> &nbsp; Date of interview: <?=$u($h['interview_date'])?></p>
<h3>I. Family Information</h3><p>Name of Household Head: <?=$u("$h[ln], $h[fn] $h[mn]")?> &nbsp; Age/Sex: <?=$u("$h[age]/$h[sex]")?> &nbsp; Birthdate: <?=$u($h['birthdate'])?></p><p>Civil status: <?=$u($h['civil'])?> Educ.: <?=$u($h['edu'])?> Occupation: <?=$u($h['occ'])?><br>Monthly income: <?=$u(peso($h['income']))?> Religion: <?=$u($h['religion'])?> Contact: <?=$u($h['contact'])?></p>
<h3>II. Family Composition</h3><table><tr><th>#</th><th>Name</th><th>Age</th><th>Sex</th><th>Educ.</th><th>Occupation</th><th>Income</th><th>Remarks</th></tr><?php foreach($M as $i=>$m)echo '<tr><td>'.($i+1).'</td><td>'.e($m['name']).'</td><td>'.e($m['age']).'</td><td>'.e($m['sex']).'</td><td>'.e($m['edu']).'</td><td>'.e($m['occ']).'</td><td>'.($m['income']>0?peso($m['income']):'').'</td><td>'.e($m['remarks']).'</td></tr>';?></table>
<p>Total household members: <?=$u($h['total_members'])?> &nbsp; Total families: <?=$u($h['total_families'])?> &nbsp; Combined monthly income: <b><?=peso(famincome($h,$M))?></b></p>
<h3>III. Housing Condition</h3><p>Type: <?=implode(' &nbsp; ',array_map(fn($o)=>$cb($h['house_type'],$o),['Concrete','Semi-concrete','Makeshift']))?><br>Ownership: <?=implode(' &nbsp; ',array_map(fn($o)=>$cb($h['house_own'],$o),['Owned','Rented','Living with Relatives','Informal Settler']))?><br>Electricity: <?=$cb($h['electricity'],'Yes').' &nbsp; '.$cb($h['electricity'],'No')?></p>
<h3>IV. Health and Nutrition</h3><p>Chronic illness: <?=$cb($h['chronic'],'Yes').' &nbsp; '.$cb($h['chronic'],'No')?> Specify: <?=$u($h['chronic_spec'])?><br>PhilHealth: <?=$cb($h['philhealth'],'Yes').' &nbsp; '.$cb($h['philhealth'],'No')?> # <?=$u($h['ph_no'])?> Category: <?=$u($h['ph_cat'])?></p>
<h3>V. Score Sheet</h3><table><tr><th>Indicator</th><th>Finding</th><th>Score</th></tr><?php foreach(IND as $k=>$l)echo '<tr><td>'.$l.'</td><td>'.e(OPT[$k][(int)$h['s_'.$k]]).'</td><td>'.(int)$h['s_'.$k].'</td></tr>';?><tr><th colspan="2">TOTAL SCORE</th><th><?=$t?> / 16</th></tr></table><p>Interpretation: <b><?=$c[0]?></b> (0–5 Not indigent; 6–10 Low-income/Vulnerable; 11–16 Indigent)</p>
<h3>Certification</h3><p>I certify that the information provided is true and correct to the best of my knowledge.</p><p style="margin-top:36px">Respondent's signature: <span class="ul" style="min-width:200px"></span> &nbsp; Interviewer/Social Worker: <span class="ul" style="min-width:200px"><?=e($h['interviewer'])?></span></p></div><?php foot();
