<?php require 'inc/lib.php';need('admin');$p=db();$msg='';
if($_SERVER['REQUEST_METHOD']==='POST'){check();$a=$_POST['a']??'';
if($a==='add'){try{if(strlen($_POST['password'])<8)throw new Exception('Password must be at least 8 characters.');$p->prepare('INSERT INTO users(username,password_hash,fullname,role) VALUES(?,?,?,?)')->execute([trim($_POST['username']),password_hash($_POST['password'],PASSWORD_DEFAULT),trim($_POST['fullname']),array_key_exists($_POST['role'],ROLES)?$_POST['role']:'official']);$msg='User added.';logact('USER',null,'Added user '.trim($_POST['username']).' ('.$_POST['role'].')');}catch(Exception $x){$msg=$x instanceof PDOException?'Username already exists.':$x->getMessage();}}
if($a==='pw'&&strlen($_POST['password'])>=8){$p->prepare('UPDATE users SET password_hash=? WHERE id=?')->execute([password_hash($_POST['password'],PASSWORD_DEFAULT),(int)$_POST['id']]);$msg='Password changed.';logact('USER',null,'Changed password of user id '.(int)$_POST['id']);}
if($a==='del'&&(int)$_POST['id']!==user()['id']){$p->prepare('DELETE FROM users WHERE id=?')->execute([(int)$_POST['id']]);$msg='User removed.';logact('USER',null,'Removed user id '.(int)$_POST['id']);}
}
$U=$p->query('SELECT * FROM users ORDER BY role,username')->fetchAll();
head('Users');?><h2>Users</h2><p><b><?=e($msg)?></b></p>
<div class="card scroll"><h3>Users</h3><table><tr><th>Username</th><th>Name</th><th>Role</th><th>New password</th><th></th></tr><?php foreach($U as $u):?><tr><td><?=e($u['username'])?></td><td><?=e($u['fullname'])?></td><td><?=e(ROLES[$u['role']])?></td><td><form method="post" class="inl"><input type="hidden" name="t" value="<?=csrf()?>"><input type="hidden" name="a" value="pw"><input type="hidden" name="id" value="<?=$u['id']?>"><input type="password" name="password" placeholder="min 8 characters" minlength="8" required><button class="btn">Change</button></form></td><td><?php if($u['id']!=user()['id']):?><form method="post" onsubmit="return confirm('Remove this user?')"><input type="hidden" name="t" value="<?=csrf()?>"><input type="hidden" name="a" value="del"><input type="hidden" name="id" value="<?=$u['id']?>"><button class="btn d">Remove</button></form><?php endif;?></td></tr><?php endforeach;?></table>
<h3>Add user</h3><form method="post" class="f"><input type="hidden" name="t" value="<?=csrf()?>"><input type="hidden" name="a" value="add"><label>Username<input name="username" required></label><label>Full name<input name="fullname" required></label><label>Password<input type="password" name="password" minlength="8" required></label><label>Role<select name="role"><?php foreach(ROLES as $k=>$l)echo "<option value='$k'>".e($l).'</option>';?></select></label><div><br><button class="btn p">Add user</button></div></form></div>
</form></div><?php foot();
